default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: cats_dealers_development
  host: localhost
  user: postgres
  password: postgres

test:
  <<: *default
  database: cats_dealers_test
  host: localhost
  user: postgres
  password: postgres

production:
  <<: *default
  database: cats_dealers_production
